name: flutter_omr
description: Flutter Optical Mark Recognition (OMR)
version: 0.0.4

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
